config/routes.rb
Rails.application.routes.draw do

  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'welcome#index'

  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash[:failed] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to GAMELAB!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?
    @current_user == @user if logged_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gamelab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row">
    <div class="col-md-9">
      <h1>GAME_LAB</h1>
    </div>
    <div class="col-md-3">
      <% if logged_in? %>
        <%= link_to "PROFILE", current_user, class: "btn btn-default" %>
        <%= link_to "ALL USERS", users_path, class: "btn btn-default" %>
        <%= link_to "LOG OUT", logout_path, method: :delete, class: "btn btn-default" %>
      <% else %>
        <%= link_to "SIGN UP", new_user_path, class: "btn btn-default" %>
        <%= link_to "SIGN IN", login_path, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>

  <%= yield %>

</body>
</html>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-3">

  </div>
  <div class="col-md-6">
    <table class="table table-condensed">
      <tr>
        <th>#</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
      </tr>
        <% @users.each do |user| %>
          <tr>
            <td><%=user.id%></td>
            <td><%=user.first_name%></td>
            <td><%=user.last_name%></td>
            <td><%=user.email%></td>
          </tr>
        <%end%>
    </table>
    <p><%= link_to "HOME", root_path, class: "btn btn-default" %></p>
  </div>
  <div class="col-md-3">

  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-4">

  </div>
  <div class="col-md-4">
    <%= form_for(@user) do |f| %>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control" %>
        <br />
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control" %>
        <br />
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
        <br />
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
        <br />
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
        <br />
      <%= f.submit "Create a user", class: "btn btn-default" %>
    <% end %>
  </div>
  <div class="col-md-4">

  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">

  </div>
  <div class="col-md-6">
    <% if current_user? %>
      <% flash.each do |message_type, message| %>
        <div class="text-success <%= message_type %>"><%= message %></div>
      <% end %>
      <br />
      <table class="table table-condensed">
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
        </tr>
          <tr>
            <td><%=@user.first_name%></td>
            <td><%=@user.last_name%></td>
            <td><%=@user.email%></td>
          </tr>
      </table>
    <% else %>
      <h4 class="text-danger">You are not allowed to see this page!</h4>
    <% end %>
    <p><%= link_to "HOME", root_path, class: "btn btn-default" %></p>
  </div>
  <div class="col-md-3">

  </div>
</div>